version: '3.8'

services:
  smartbch:
    build: .
    command: start --skip-sanity-check=true
    ports:
      - "8545:8545"
    restart: always
    volumes:
      - smartbch_data:/root/.follower
volumes:
    smartbch_data:
